export { default as SideBar } from './SideBar/index.vue'
export { default as NavBar } from './NavBar/index.vue'
export { default as AppMain } from './AppMain/index.vue'
export { default as TagsView } from './TagsView/index.vue'
export { default as Settings } from './Settings/index.vue'